### PR TITLE
Stop using watchdog.getItem() as it throws when the item is not registered yet

### LINKED ISSUE #177: Using disabled property with context watchdog causes a crash
Watchdog crashes when ckeditor component is initialized with `disabled` property and `watchdog` property together.

Below code is fired when `disabled` property of the component is read:

```plaintext
public setDisabledState( isDisabled: boolean ): void {
	// If already initialized.
	if ( this.editorInstance ) {
		this.editorInstance.isReadOnly = isDisabled;
	}

	// Store the state anyway to use it once the editor is created.
	this.initialIsDisabled = isDisabled;
}
```

`this.editorInstance` is a getter:

```plaintext
public get editorInstance(): CKEditor5.Editor | null {
	if ( this.editorWatchdog ) {
		return this.editorWatchdog.editor;
	}

	if ( this.watchdog ) {
		return this.watchdog.getItem( this.id );
	}

	return null;
}
```

Unfortunately, at the time `setDisabledState` is called, the editor is not yet added to the watchdog, so `this.watchdog.getItem` throws an error.

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Changing the `disabled` property on the `<ckeditor>` component while using the `watchdog` property won't throw an error anymore. Closes #177.

---

### Additional information

*   Changed internal component property `initialIsDisabled` to `initiallyDisabled`.

### CODE REVIEW

File: src/app/watchdog-demo/watchdog-demo.ts [hunk 1]
```diff
@@ -16,6 +16,8 @@ export class WatchdogDemoComponent {
 	public watchdog: any;
 	public ready = false;
 
+	public isDisabled = true;
```
Comment (scofalik) [inline src/app/watchdog-demo/watchdog-demo.ts]: I am not sure if it is good that the demo is disabled by default. I'd go with `false`. Just check it manually and leave the unit test as you did.

**Comment by scofalik** [comment]
I have just one small comment and we can merge it and release it.
